const ENTITY_TYPES=Object.freeze(['customer','parcel_active','parcel_archive','claim','profile_settings_v35']);const DEVICE_KEY='lz35.deviceId',OUTBOX_KEY='lz35.sync.outbox.v38';
function deviceId(){let v=localStorage.getItem(DEVICE_KEY);if(v)return v;v=`dev-${crypto.randomUUID()}`;localStorage.setItem(DEVICE_KEY,v);return v}function timestamp(i){return i?.modifiedAt||i?.updatedAt||i?.statusUpdatedAt||i?.archivedAt||i?.createdAt||''}function newer(a,b){if(!a)return b;if(!b)return a;const ta=Date.parse(timestamp(a))||0,tb=Date.parse(timestamp(b))||0;return tb>ta?b:a}function merge(local=[],cloud=[]){const m=new Map();for(const i of local)if(i?.id)m.set(i.id,i);for(const i of cloud)if(i?.id)m.set(i.id,newer(m.get(i.id),i));return [...m.values()]}
function localIndex(state,profileId){const m=new Map(),add=(type,item)=>item?.id&&m.set(`${type}:${item.id}`,{item,modifiedAt:timestamp(item)});state.customers.forEach(i=>add('customer',i));state.parcels.forEach(i=>add('parcel_active',i));state.archive.forEach(i=>add('parcel_archive',i));(state.claims||[]).forEach(i=>add('claim',i));add('profile_settings_v35',{id:profileId,...(state.profileSettings||{})});return m}
function readOutbox(){try{return JSON.parse(localStorage.getItem(OUTBOX_KEY)||'[]')}catch{return[]}}function writeOutbox(v){localStorage.setItem(OUTBOX_KEY,JSON.stringify(v.slice(-25)))}function queue(reason='sync'){const q=readOutbox();q.push({id:crypto.randomUUID(),reason,at:new Date().toISOString()});writeOutbox(q);return q.length}
const COLLECTION_FOR=Object.freeze({customer:'customers',parcel_active:'parcels',parcel_archive:'archive',claim:'claims'});
function deviceList(state,rows){const seen=new Map((Array.isArray(state.sync?.devices)?state.sync.devices:[]).filter(d=>d?.id).map(d=>[String(d.id),d]));for(const r of rows||[]){if(!r.device_id)continue;const id=String(r.device_id);const lastSeen=String(r.modified_at||'');const prev=seen.get(id);if(!prev||String(prev.lastSeen||'')<lastSeen)seen.set(id,{id,lastSeen});}return [...seen.values()].slice(-25)}
export function createSyncService({supabase,store}){async function tracking(client,state,modifiedAt){const rows=[...state.parcels.map(item=>({item,archived:false})),...state.archive.map(item=>({item,archived:true}))].filter(x=>x.item.trackingToken).map(({item,archived})=>({tracking_token:item.trackingToken,workspace_id:state.workspace.id,pick_id:item.pickId,status:item.status||'ready',archived,updated_at:item.statusUpdatedAt||item.archivedAt||item.modifiedAt||modifiedAt}));if(!rows.length)return{count:0};const{error}=await client.from('public_tracking_v35').upsert(rows,{onConflict:'tracking_token'});return{count:rows.length,error:error||null}}
async function pushSnapshot({reason='manual'}={}){const state=store.getState();if(!state.session||!state.workspace?.id){queue(reason);return{status:'local-only',pending:readOutbox().length}}const client=await supabase.connect(),profileId=state.workspace.profileId||'ps_default',modifiedAt=new Date().toISOString(),sourceDevice=deviceId();const row=(entity_type,item)=>({workspace_id:state.workspace.id,profile_id:profileId,entity_type,entity_id:item.id,payload:item,modified_at:timestamp(item)||modifiedAt,deleted_at:null,device_id:sourceDevice});const settings={id:profileId,...(state.profileSettings||{})};const rows=[...state.customers.map(i=>row('customer',i)),...state.parcels.map(i=>row('parcel_active',i)),...state.archive.map(i=>row('parcel_archive',i)),...(state.claims||[]).map(i=>row('claim',i)),row('profile_settings_v35',settings)];store.setState({sync:{...state.sync,status:'syncing',conflict:false,pending:readOutbox().length}});const{data,error}=await client.rpc('apply_sync_changes',{p_workspace_id:state.workspace.id,p_changes:rows});if(error){const pending=queue(reason);store.setState({sync:{status:'error',conflict:false,pending,message:error.message}});throw error}let tr={count:0};try{tr=await tracking(client,state,modifiedAt)}catch(e){tr={count:0,error:e}}writeOutbox([]);store.setState({sync:{status:'synced',conflict:false,pending:0,tracking:tr.error?'deferred':'published',lastSuccess:modifiedAt}});return{status:'synced',records:Number(data??rows.length),tracking:tr.count,trackingStatus:tr.error?'deferred':'published'}}
async function pullSnapshot({force=false}={}){const state=store.getState();if(!state.session||!state.workspace?.id)return{status:'local-only'};const client=await supabase.connect(),profileId=state.workspace.profileId||'ps_default';store.setState({sync:{...state.sync,status:'syncing',conflict:false}});const{data,error}=await client.from('sync_entities').select('entity_type,entity_id,payload,modified_at,deleted_at,device_id').eq('workspace_id',state.workspace.id).eq('profile_id',profileId).in('entity_type',ENTITY_TYPES).is('deleted_at',null).order('modified_at',{ascending:true});if(error){store.setState({sync:{status:'error',conflict:false,pending:readOutbox().length,message:error.message}});throw error}if(!force){const local=localIndex(state,profileId),sourceDevice=deviceId();const conflicts=(data||[]).filter(r=>{const l=local.get(`${r.entity_type}:${r.entity_id}`);if(!l?.modifiedAt||!r.modified_at||r.device_id===sourceDevice)return false;if(l.item?.syncKeepLocalAt&&Date.parse(l.item.syncKeepLocalAt)>=Date.parse(r.modified_at))return false;return Date.parse(l.modifiedAt)>Date.parse(r.modified_at)}).map(r=>{const l=local.get(`${r.entity_type}:${r.entity_id}`);return{entityType:r.entity_type,entityId:r.entity_id,localModifiedAt:l?.modifiedAt||'',cloudModifiedAt:String(r.modified_at||''),localPayload:l?.item||null,cloudPayload:r.payload}});if(conflicts.length){store.setState({sync:{...state.sync,status:'conflict',conflict:true,conflicts,devices:deviceList(state,data),pending:readOutbox().length}});return{status:'conflict',records:(data||[]).length,conflicts}}}const cloud={customers:[],parcels:[],archive:[],claims:[]};let settings=null;for(const r of data||[]){if(r.entity_type==='customer')cloud.customers.push(r.payload);if(r.entity_type==='parcel_active')cloud.parcels.push(r.payload);if(r.entity_type==='parcel_archive')cloud.archive.push(r.payload);if(r.entity_type==='claim')cloud.claims.push(r.payload);if(r.entity_type==='profile_settings_v35')settings=r.payload}const next={customers:force?cloud.customers:merge(state.customers,cloud.customers),parcels:force?cloud.parcels:merge(state.parcels,cloud.parcels),archive:force?cloud.archive:merge(state.archive,cloud.archive),claims:force?cloud.claims:merge(state.claims||[],cloud.claims),profileSettings:settings||state.profileSettings,sync:{status:'synced',conflict:false,conflicts:[],devices:deviceList(state,data),pending:readOutbox().length,lastSuccess:new Date().toISOString()}};store.setState(next);return{status:'synced',records:(data||[]).length,protectedLocal:!force}}
async function flush(){if(!readOutbox().length)return{status:'empty'};return pushSnapshot({reason:'outbox-replay'})}function pending(){return readOutbox().length}
async function resolveConflicts(resolutions=[]){const state=store.getState();const known=new Map((Array.isArray(state.sync?.conflicts)?state.sync.conflicts:[]).filter(c=>c?.entityType&&c?.entityId).map(c=>[`${c.entityType}:${c.entityId}`,c]));const choices=new Map((resolutions||[]).filter(r=>r?.entityId).map(r=>[`${r.entityType}:${r.entityId}`,r.choice==='cloud'?'cloud':'local']));const now=new Date().toISOString();const next={customers:[...(state.customers||[])],parcels:[...(state.parcels||[])],archive:[...(state.archive||[])],claims:[...(state.claims||[])],profileSettings:state.profileSettings};let local=0,cloud=0;
 for(const[key,conflict]of known){const choice=choices.get(key);if(!choice)continue;
  if(conflict.entityType==='profile_settings_v35'){if(choice==='cloud'&&conflict.cloudPayload)next.profileSettings={...conflict.cloudPayload};if(choice==='cloud')cloud+=1;else local+=1;continue}
  const collection=COLLECTION_FOR[conflict.entityType];if(!collection)continue;const index=next[collection].findIndex(item=>item?.id===conflict.entityId);
  if(choice==='cloud'){if(conflict.cloudPayload){if(index>=0)next[collection][index]={...conflict.cloudPayload};else next[collection].push({...conflict.cloudPayload});}cloud+=1}
  else{if(index>=0)next[collection][index]={...next[collection][index],modifiedAt:now,syncKeepLocalAt:now};local+=1}}
 store.setState({...next,sync:{...state.sync,status:'resolved',conflict:false,conflicts:[],pending:readOutbox().length}});return{status:'resolved',local,cloud}}
function pendingChanges(limit=100){const state=store.getState();const profileId=state.workspace?.profileId||'ps_default';const last=Date.parse(state.sync?.lastSuccess||'')||0;const out=[];for(const[key,entry]of localIndex(state,profileId)){const[type,id]=key.split(':');const at=Date.parse(entry.modifiedAt)||0;if(last&&at<=last)continue;out.push({type,id,label:String(entry.item?.name||entry.item?.pickId||id||'record'),modifiedAt:entry.modifiedAt||''});if(out.length>=Math.max(1,Number(limit)||100))break}return out}
return{pushSnapshot,pullSnapshot,flush,pending,queue,deviceId,resolveConflicts,pendingChanges}}
