import { action, field } from '../components/form.js';
import { heading, textStack } from '../components/view.js';

function shipmentHistory(state, customerId) {
  const all = [...state.parcels, ...state.archive].filter((item) => item.customerId === customerId || item.customer?.id === customerId);
  if (!all.length) return null;
  return [...all].sort((a, b) => String(b.createdAt || b.archivedAt || '').localeCompare(String(a.createdAt || a.archivedAt || '')))[0];
}

function clean(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim();
}

function phoneKey(value) {
  const digits = clean(value).replace(/\D/g, '');
  if (!digits) return '';
  return digits.startsWith('261') && digits.length === 12 ? `0${digits.slice(3)}` : digits;
}

function textKey(value) {
  return clean(value).normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
}

function customerKey(customer) {
  const phone = phoneKey(customer.phone);
  if (phone) return `p:${phone}`;
  return `n:${textKey(customer.name)}|a:${textKey(customer.area)}|d:${textKey(customer.address)}`;
}

function parseAddressBook(payload) {
  const rows = Array.isArray(payload) ? payload : payload?.customers;
  if (!Array.isArray(rows)) throw new Error('No customers array found in this file.');

  return rows.map((row) => ({
    name: clean(row?.name),
    phone: clean(row?.phone),
    area: clean(row?.area),
    address: clean(row?.address),
  })).filter((row) => row.name && (row.phone || row.area || row.address));
}

export function createCustomersModule({ store }) {
  let importMessage = '';

  return {
    render(state) {
      const section = document.createElement('section');
      section.className = 'screen';
      section.append(heading('Customers', 'Saved customers and address book.'));

      const selected = new Set();
      const toolbar = document.createElement('div');
      toolbar.className = 'button-row';
      const removeSelected = action('Delete selected');
      removeSelected.disabled = true;
      removeSelected.addEventListener('click', () => {
        store.update((current) => ({ ...current, customers: current.customers.filter((item) => !selected.has(item.id)) }));
      });

      const importInput = document.createElement('input');
      importInput.type = 'file';
      importInput.accept = 'application/json,.json';
      importInput.hidden = true;
      importInput.setAttribute('aria-label', 'Address Book import file');
      const importButton = action('Import Address Book', 'primary');
      const importStatus = document.createElement('p');
      importStatus.className = 'helper-text';
      importStatus.textContent = importMessage;
      importButton.addEventListener('click', () => importInput.click());
      importInput.addEventListener('change', async () => {
        const file = importInput.files?.[0];
        if (!file) return;
        importInput.value = '';
        try {
          const incoming = parseAddressBook(JSON.parse(await file.text()));
          const existingKeys = new Set(state.customers.map(customerKey));
          const incomingKeys = new Set();
          const now = new Date().toISOString();
          const imported = [];
          let skipped = 0;

          for (const row of incoming) {
            const key = customerKey(row);
            if (existingKeys.has(key) || incomingKeys.has(key)) {
              skipped += 1;
              continue;
            }
            incomingKeys.add(key);
            imported.push({
              id: crypto.randomUUID(),
              name: row.name,
              phone: row.phone,
              area: row.area,
              address: row.address,
              createdAt: now,
              modifiedAt: now,
            });
          }

          importMessage = `${imported.length} customer${imported.length === 1 ? '' : 's'} imported${skipped ? ` · ${skipped} duplicate${skipped === 1 ? '' : 's'} skipped` : ''}. IDs were generated by 3.5; legacy IDs and notes were ignored.`;
          if (imported.length) {
            store.update((current) => ({ ...current, customers: [...current.customers, ...imported] }));
          } else {
            importStatus.textContent = importMessage;
          }
        } catch (error) {
          importMessage = `Import rejected: ${error.message}`;
          importStatus.textContent = importMessage;
        }
      });

      toolbar.append(importButton, importInput, removeSelected);
      section.append(toolbar, importStatus);

      const list = document.createElement('div');
      list.className = 'card-list';
      if (!state.customers.length) {
        const empty = document.createElement('div');
        empty.className = 'empty-state';
        empty.textContent = 'No saved customers yet.';
        list.append(empty);
      }

      for (const customer of state.customers) {
        const card = document.createElement('article');
        card.className = 'card';
        card.dataset.customerId = customer.id;

        const chooser = document.createElement('input');
        chooser.type = 'checkbox';
        chooser.setAttribute('aria-label', `Select ${customer.name}`);
        chooser.addEventListener('change', () => {
          if (chooser.checked) selected.add(customer.id);
          else selected.delete(customer.id);
          removeSelected.disabled = selected.size === 0;
        });

        const history = shipmentHistory(state, customer.id);
        const text = textStack([
          ['strong', customer.name],
          ['span', customer.phone || 'No phone'],
          ...(customer.area ? [['span', customer.area]] : []),
          ['span', customer.address || 'No address'],
          ...(history ? [['small', `Previous shipment: ${history.pickId || 'unknown'} · ${history.status || 'unknown'}`]] : []),
        ]);

        const buttons = document.createElement('div');
        buttons.className = 'button-row';
        const use = action('Use for label', 'primary');
        const edit = action('Edit');

        use.addEventListener('click', () => {
          store.update((next) => ({ ...next, route: 'label', labelDraft: { ...next.labelDraft, step: 2, customerId: customer.id, customer: { name: customer.name, phone: customer.phone, address: customer.address } } }));
          location.hash = '#/label';
        });

        edit.addEventListener('click', () => {
          const form = document.createElement('div');
          form.className = 'workspace-card';
          const name = field('Name', 'customerEditName', customer.name);
          const phone = field('Phone', 'customerEditPhone', customer.phone || '', { inputmode: 'tel' });
          const area = field('Area', 'customerEditArea', customer.area || '');
          const address = field('Address', 'customerEditAddress', customer.address || '', { multiline: true });
          const save = action('Save customer', 'primary');
          const cancel = action('Cancel');
          const row = document.createElement('div');
          row.className = 'button-row';
          save.addEventListener('click', () => {
            const nextName = name.input.value.trim();
            if (!nextName) return;
            store.update((current) => ({
              ...current,
              customers: current.customers.map((item) => item.id === customer.id ? { ...item, name: nextName, phone: phone.input.value.trim(), area: area.input.value.trim(), address: address.input.value.trim(), modifiedAt: new Date().toISOString() } : item),
            }));
          });
          cancel.addEventListener('click', () => store.setState({ ui: { ...store.getState().ui, notice: '' } }));
          row.append(save, cancel);
          form.append(name.wrap, phone.wrap, area.wrap, address.wrap, row);
          card.replaceChildren(form);
        });

        buttons.append(use, edit);
        card.append(chooser, text, buttons);
        list.append(card);
      }
      section.append(list);
      return section;
    },
  };
}
